### PR TITLE
updated to pull quotes from firebase and randomly pick one to show

### PR DESCRIPTION
**Pull request by jonathanpeterwu**
@amgando 

Hey 

I've integrated firebase to be our quote store. Right now its read/write for anyone. 

Here's the link:
https://dbc-coaches.firebaseio.com/#

The javascript right now on the index page pulls from firebase to generate quotes

### CODE REVIEW

**Comment by amgando** [comment]
couldn't view the firebase link bc my account isn't authorised.  can you authorise sherif@amgando.org?

**Comment by jonathanpeterwu** [comment]
@amgando 

Hey added you w/ that email. User auth looks specific to the database.

https://dbc-coaches.firebaseio.com/#
Username: sherif@amgando.org  
Password: password (I would do a password reset lol)

**Comment by jonathanpeterwu** [comment]
Btw. If the coaches feedback form is ready to go let me know and I can integrate it

**Comment by amgando** [comment]
still can't view this URL

**Comment by jonathanpeterwu** [comment]
@amgando  I changed auth to allow anonymous use I think and sent you a password reset if that doesn't work

**Comment by amgando** [comment]
still not working for me.  might be better to get on the phone for this

**Pull request closed without merging**
