### PR TITLE
Sam consolidate html

### PR DESCRIPTION
**Pull request by SamSamskies**
@jonathanpeterwu, @amgando, @NathanielWroblewski Converted the page into a SPA to get rid of the unnecessary duplicated HTML.

Let me know what you guys think. I didn't get fancy with any animations or anything, but at least navigating the site is snappier without the page refreshes.

### CODE REVIEW

**Comment by SamSamskies** [comment]
Actually, I just realized you can't bookmark the links. Hold off on reviewing this.

**Comment by SamSamskies** [comment]
Okay, this is ready to be looked at again. Links can now be bookmarked. For example, you can bookmark the team page using either '/#team' or '/index.html#team' 

If you want to add new sections, just add a new section with a unique id for the section. You'll also need to add a class of '.main-content' to that section. Any links to this section should use the id as the href. I can add this to the README if necessary. My router uses the id of the section to show the section you want.

**Comment by NathanielWroblewski** [comment]
So, I'm totally cool with fixing the duplicated code problem, and I think you did this well by introducing the minimum amount of backbone to fix this.  My concerns are with existing links on any externals pages to old routes.  I'd also hope we can add the changes in that I made to the roster, including the CSS.  What are our thoughts on any fallbacks for people that have js disabled?

**Comment by NathanielWroblewski** [comment]
"Backbone"

**Comment by SamSamskies** [comment]
I can fix the backwards links easily.

I don't think it's necessary to support people who have JS disabled. Why
would they be at DBC if they have JS disabled?

**Comment by SamSamskies** [comment]
@NathanielWroblewski Now all old links are forwarded to their respective pages. We can wait on merging this until we get your branch in. That way I can fix the merge conflicts and make sure your changes are all good.

Also, if anyone has a better solution for consolidating the HTML, I don't mind scrapping this.

**Comment by SamSamskies** [comment]
@NathanielWroblewski If we are going to support a fallback for people with JS disabled, I say we write a loop that draws a 1000 alert boxes all over the screen saying... "Stop living in 1997 and turn on your JS. Thank you."

**Comment by jonathanpeterwu** [comment]
@SamSamskies  hey I merged Nate's PR in first. if you want to update this branch and push it up I'm ready to merge this

**Comment by jonathanpeterwu** [comment]
https://www.dropbox.com/s/b7mtbnoxh0pw9qk/Screenshot%202014-11-05%2015.11.21.png

**Comment by amgando** [comment]
can you alpha sort by first name please?

**Comment by jonathanpeterwu** [comment]
sure. just want to make sure you are being serious.

**Comment by SamSamskies** [comment]
@jonathanpeterwu I'll fix the conflicts when I get home tonight after the DBC alumni happy hour.

**Comment by jonathanpeterwu** [comment]
awesome thanks. the two major changes are on gh-pages branch (team.html, student.html)

**Comment by SamSamskies** [comment]
@jonathanpeterwu This is ready to be looked at again.

**Comment by jonathanpeterwu** [comment]
@SamSamskies  this looks awesome. QA looks good. I'll merge it in now

**Pull request merged**
